/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package svacee.view;

/**
 *
 * @author Ana Letícia, Lucas Diego e Matheus Quilles
 */
public class SvaceeMainForm extends javax.swing.JFrame {

    /**
     * Creates new form SvaceeMainForm
     */
    public SvaceeMainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPainel = new javax.swing.JPanel();
        jtbBarraFerramentas = new javax.swing.JToolBar();
        jbObterDadosCSV = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jbTabelaDados = new javax.swing.JButton();
        jbGraficoConsumo = new javax.swing.JButton();
        jbSobre = new javax.swing.JButton();
        jlImg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmArquivo = new javax.swing.JMenu();
        jmiObterDadosCSV = new javax.swing.JMenuItem();
        jmiSair = new javax.swing.JMenuItem();
        jmVisualizar = new javax.swing.JMenu();
        jmiTabelaDados = new javax.swing.JMenuItem();
        jmiGraficoConsumo = new javax.swing.JMenuItem();
        jmAjuda = new javax.swing.JMenu();
        jmiSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Inicial");

        jtbBarraFerramentas.setFloatable(false);
        jtbBarraFerramentas.setRollover(true);
        jtbBarraFerramentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jbObterDadosCSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/svacee/img/lista24.png"))); // NOI18N
        jbObterDadosCSV.setFocusable(false);
        jbObterDadosCSV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbObterDadosCSV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbBarraFerramentas.add(jbObterDadosCSV);

        jbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/svacee/img/sair24.png"))); // NOI18N
        jbSair.setFocusable(false);
        jbSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbBarraFerramentas.add(jbSair);

        jbTabelaDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/svacee/img/tabela24.png"))); // NOI18N
        jbTabelaDados.setFocusable(false);
        jbTabelaDados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbTabelaDados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbBarraFerramentas.add(jbTabelaDados);

        jbGraficoConsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/svacee/img/grafico24.png"))); // NOI18N
        jbGraficoConsumo.setFocusable(false);
        jbGraficoConsumo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbGraficoConsumo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbBarraFerramentas.add(jbGraficoConsumo);

        jbSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/svacee/img/sobre24.png"))); // NOI18N
        jbSobre.setFocusable(false);
        jbSobre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSobre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbBarraFerramentas.add(jbSobre);

        jlImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/svacee/img/graficohome.jpg"))); // NOI18N

        javax.swing.GroupLayout jPainelLayout = new javax.swing.GroupLayout(jPainel);
        jPainel.setLayout(jPainelLayout);
        jPainelLayout.setHorizontalGroup(
            jPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbBarraFerramentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPainelLayout.setVerticalGroup(
            jPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPainelLayout.createSequentialGroup()
                .addComponent(jtbBarraFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlImg))
        );

        jMenuBar1.setBackground(new java.awt.Color(1, 1, 1));

        jmArquivo.setText("Arquivo");

        jmiObterDadosCSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/svacee/img/lista.png"))); // NOI18N
        jmiObterDadosCSV.setText("Obter Dados de CSV");
        jmArquivo.add(jmiObterDadosCSV);

        jmiSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/svacee/img/sair.png"))); // NOI18N
        jmiSair.setText("Sair");
        jmArquivo.add(jmiSair);

        jMenuBar1.add(jmArquivo);

        jmVisualizar.setText("Visualizar");

        jmiTabelaDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/svacee/img/tabela.png"))); // NOI18N
        jmiTabelaDados.setText("Tabela de Dados");
        jmiTabelaDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTabelaDadosActionPerformed(evt);
            }
        });
        jmVisualizar.add(jmiTabelaDados);

        jmiGraficoConsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/svacee/img/grafico.png"))); // NOI18N
        jmiGraficoConsumo.setText("Gráfico de Consumo");
        jmVisualizar.add(jmiGraficoConsumo);

        jMenuBar1.add(jmVisualizar);

        jmAjuda.setText("Ajuda");

        jmiSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/svacee/img/sobre.png"))); // NOI18N
        jmiSobre.setText("Sobre");
        jmAjuda.add(jmiSobre);

        jMenuBar1.add(jmAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiTabelaDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTabelaDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiTabelaDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SvaceeMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SvaceeMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SvaceeMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SvaceeMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SvaceeMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPainel;
    private javax.swing.JButton jbGraficoConsumo;
    private javax.swing.JButton jbObterDadosCSV;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbSobre;
    private javax.swing.JButton jbTabelaDados;
    private javax.swing.JLabel jlImg;
    private javax.swing.JMenu jmAjuda;
    private javax.swing.JMenu jmArquivo;
    private javax.swing.JMenu jmVisualizar;
    private javax.swing.JMenuItem jmiGraficoConsumo;
    private javax.swing.JMenuItem jmiObterDadosCSV;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiSobre;
    private javax.swing.JMenuItem jmiTabelaDados;
    private javax.swing.JToolBar jtbBarraFerramentas;
    // End of variables declaration//GEN-END:variables
}
